[package]
name = "rust-discord"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
google-calendar = "0.7.0"
dotenv = "0.15.0"
time = { version = "0.3.36", features = ["macros"] }
